development:
  adapter:  postgresql
  encoding: unicode
  database: bicycle_development
  pool:     5

test:
  adapter:  postgresql
  encoding: unicode
  database: bicycle_test
  pool:     5

production:
  adapter:  postgresql
  encoding: unicode
  database: bicycle_production
  pool:     5
