development:
  adapter:  postgresql
  encoding: unicode
  database: bicycle_development
  pool:     5

test:
  adapter:  postgresql
  encoding: unicode
  database: bicycle_test
  pool:     5

production:
  adapter: postgresql
  encoding: unicode
  pool:     5
  database: <%= ENV['RDS_DB_NAME'] %>
  username: <%= ENV['RDS_USERNAME'] %>
  password: <%= ENV['RDS_PASSWORD'] %>
  host: <%= ENV['RDS_HOSTNAME'] %>
  port: <%= ENV['RDS_PORT'] %>
