# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  domain_name: example.com
  secret_key_base: e5d2d50c18428c0d163bca82775d3d0669f6c88bdb59efaee2f0b2ca7c00bff7675f30729c558a26eb8b4d5105963becfc417a7790d56fc1b0166825e6819c53

test:
  secret_key_base: 31b91a6d5d3f5db46b2eb363998f4aca7bd767494b0f7700c8f054c7b1ba982beaa5a12721ac209c243b53fddd89ad90bb6394d5c49aad18a102037e94630672

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  domain_name: <%= ENV["DOMAIN_NAME"] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
